POST http://localhost:3000/auth/refresh-token
Cookie: refresh_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc2Nzc1ODg0MCwiZXhwIjoxNzY4MzYzNjQwfQ.1EvSN4iCf85O_zJEEdtqhYZaW_YFZVSPqDYzKF-rZdU"